name: Microservice Patterns CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build all services
      run: docker-compose -f docker-compose.yml build

    - name: Start all services
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for containers to initialize
      run: sleep 30

    - name: Check service status
      run: docker-compose ps

    - name: Tear down
      if: always()
      run: docker-compose down
